/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fichero_secuencial;

import static fichero_secuencial.Fichero_secuencial1.grabarDatos;
import java.awt.Dimension;
import java.io.*;
import javax.swing.JFrame;


/**
 *
 * @author Sergio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocation(300, 300);
        boolean paco=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeerEscribir = new javax.swing.JDialog();
        ArchivoSecuencial1 = new javax.swing.JPanel();
        LeerFichero = new javax.swing.JButton();
        EscribirFichero = new javax.swing.JButton();
        BuscarTexto = new javax.swing.JButton();
        ArchivoLeer = new javax.swing.JPanel();
        AceptarLeer = new javax.swing.JButton();
        NombreFicheroLeer = new javax.swing.JTextField();
        TextoLeer = new javax.swing.JLabel();
        panelArchivoLeer = new javax.swing.JTextField();
        ArchivoEscribir = new javax.swing.JPanel();
        AceptarEscribir = new javax.swing.JButton();
        NombreFicheroEscribir = new javax.swing.JTextField();
        TextoEscribir = new javax.swing.JLabel();
        ArchivoEscribir1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        CopiarFichero = new javax.swing.JButton();
        CrearFichero = new javax.swing.JButton();
        ArchivoAleatorio = new javax.swing.JButton();
        ArchivoSecuencial = new javax.swing.JButton();

        LeerFichero.setText("Leer Fichero");
        LeerFichero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LeerFicheroMousePressed(evt);
            }
        });
        LeerFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        EscribirFichero.setText("Escribir Fichero");
        EscribirFichero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscribirFicheroMousePressed(evt);
            }
        });

        BuscarTexto.setText("Buscar Texto");

        javax.swing.GroupLayout ArchivoSecuencial1Layout = new javax.swing.GroupLayout(ArchivoSecuencial1);
        ArchivoSecuencial1.setLayout(ArchivoSecuencial1Layout);
        ArchivoSecuencial1Layout.setHorizontalGroup(
            ArchivoSecuencial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArchivoSecuencial1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LeerFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(EscribirFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(ArchivoSecuencial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ArchivoSecuencial1Layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(BuscarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        ArchivoSecuencial1Layout.setVerticalGroup(
            ArchivoSecuencial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoSecuencial1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoSecuencial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscribirFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeerFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(ArchivoSecuencial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ArchivoSecuencial1Layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(BuscarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        AceptarLeer.setText("Aceptar");
        AceptarLeer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AceptarLeerMousePressed(evt);
            }
        });

        TextoLeer.setText("Nombre fichero:");

        javax.swing.GroupLayout ArchivoLeerLayout = new javax.swing.GroupLayout(ArchivoLeer);
        ArchivoLeer.setLayout(ArchivoLeerLayout);
        ArchivoLeerLayout.setHorizontalGroup(
            ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoLeerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArchivoLeer)
                    .addGroup(ArchivoLeerLayout.createSequentialGroup()
                        .addComponent(TextoLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(NombreFicheroLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AceptarLeer)))
                .addContainerGap())
        );
        ArchivoLeerLayout.setVerticalGroup(
            ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoLeerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ArchivoLeerLayout.createSequentialGroup()
                        .addComponent(TextoLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AceptarLeer)
                        .addComponent(NombreFicheroLeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(panelArchivoLeer, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        AceptarEscribir.setText("Aceptar");
        AceptarEscribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AceptarEscribirMousePressed(evt);
            }
        });

        TextoEscribir.setText("Nombre fichero:");

        javax.swing.GroupLayout ArchivoEscribirLayout = new javax.swing.GroupLayout(ArchivoEscribir);
        ArchivoEscribir.setLayout(ArchivoEscribirLayout);
        ArchivoEscribirLayout.setHorizontalGroup(
            ArchivoEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoEscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(NombreFicheroEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AceptarEscribir)
                .addContainerGap())
        );
        ArchivoEscribirLayout.setVerticalGroup(
            ArchivoEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ArchivoEscribirLayout.createSequentialGroup()
                        .addComponent(TextoEscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ArchivoEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AceptarEscribir)
                        .addComponent(NombreFicheroEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton1.setText(" Escribir al final del fichero");

        jButton2.setText("Sobreescribir fichero");

        javax.swing.GroupLayout ArchivoEscribir1Layout = new javax.swing.GroupLayout(ArchivoEscribir1);
        ArchivoEscribir1.setLayout(ArchivoEscribir1Layout);
        ArchivoEscribir1Layout.setHorizontalGroup(
            ArchivoEscribir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribir1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        ArchivoEscribir1Layout.setVerticalGroup(
            ArchivoEscribir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribir1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(ArchivoEscribir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LeerEscribirLayout = new javax.swing.GroupLayout(LeerEscribir.getContentPane());
        LeerEscribir.getContentPane().setLayout(LeerEscribirLayout);
        LeerEscribirLayout.setHorizontalGroup(
            LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoLeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoSecuencial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ArchivoEscribir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        LeerEscribirLayout.setVerticalGroup(
            LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoLeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoSecuencial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ArchivoEscribir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CopiarFichero.setText("Copiar fichero");

        CrearFichero.setText("Crear fichero o carpeta");

        ArchivoAleatorio.setText("Archivo aleatorio");

        ArchivoSecuencial.setText("Archivo secuencial");
        ArchivoSecuencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ArchivoSecuencialMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArchivoSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ArchivoAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(CopiarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArchivoSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(ArchivoAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CrearFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(CopiarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        
    private void ArchivoSecuencialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivoSecuencialMousePressed
        ArchivoLeer.setVisible(false);
        ArchivoEscribir.setVisible(false);
        ArchivoEscribir1.setVisible(false);
        
        LeerEscribir.setVisible(true);
        LeerEscribir.setLocation(300, 300);
        LeerEscribir.setSize(400, 300);
        ArchivoSecuencial1.setVisible(true);

    }//GEN-LAST:event_ArchivoSecuencialMousePressed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void LeerFicheroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeerFicheroMousePressed
        ArchivoSecuencial1.setVisible(false);
        ArchivoLeer.setVisible(true);
        LeerEscribir.setSize(488, 310);
        
    }//GEN-LAST:event_LeerFicheroMousePressed

    private void AceptarLeerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarLeerMousePressed
        leerDatos(NombreFicheroLeer.getText());
        
    }//GEN-LAST:event_AceptarLeerMousePressed

    private void EscribirFicheroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscribirFicheroMousePressed
        ArchivoSecuencial1.setVisible(false);
        ArchivoEscribir.setVisible(true);
        ArchivoEscribir.setLocation(300, 300);
        LeerEscribir.setSize(488, 91);
    }//GEN-LAST:event_EscribirFicheroMousePressed

    private void AceptarEscribirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarEscribirMousePressed
        ArchivoEscribir.setVisible(false);
        ArchivoEscribir1.setVisible(true);
        ArchivoEscribir1.setLocation(300, 300);
        LeerEscribir.setSize(400, 300);
        
        rutaFichero(NombreFicheroEscribir.getText());
    }//GEN-LAST:event_AceptarEscribirMousePressed
   
    

    
    public static void grabarDatos(String archivo, String datos){
        try{

            FileWriter fw = new FileWriter(archivo,false);

            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(datos + "\n");
             bw.close();
             }
        catch(java.io.IOException ioex){}
    } 
    

    public static void rutaFichero(String archivo){
        try{
            FileReader fr = new FileReader(archivo);
            BufferedReader entrada = new BufferedReader(fr);
        }
        
        catch(java.io.FileNotFoundException fnfex){
            
        System.out.println("Archivo no encontrado!!!"); 
        }
        catch(java.io.IOException ioex){}
    }

    public static void leerDatos(String archivo){
        
        
        try{
            String texto= new String();
            FileReader fr = new FileReader(archivo);
            BufferedReader entrada = new BufferedReader(fr);
            String s;
            
            
            while((s = entrada.readLine() )!=null)
                texto += s + "\n";
            System.out.println("\nDatos leidos del archivo con READLINE:"
                     + " \n" + texto + "tamaño del fichero: \n"+texto.length());
          
            System.out.print((char) entrada.read());
            entrada.close();
            
        }
        
        catch(java.io.FileNotFoundException fnfex){   
        System.out.println("Archivo no encontrado!!!"); 
        }
        catch(java.io.IOException ioex){} 
        }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarEscribir;
    private javax.swing.JButton AceptarLeer;
    private javax.swing.JButton ArchivoAleatorio;
    private javax.swing.JPanel ArchivoEscribir;
    private javax.swing.JPanel ArchivoEscribir1;
    private javax.swing.JPanel ArchivoLeer;
    private javax.swing.JButton ArchivoSecuencial;
    private javax.swing.JPanel ArchivoSecuencial1;
    private javax.swing.JButton BuscarTexto;
    private javax.swing.JButton CopiarFichero;
    private javax.swing.JButton CrearFichero;
    private javax.swing.JButton EscribirFichero;
    private javax.swing.JDialog LeerEscribir;
    private javax.swing.JButton LeerFichero;
    private javax.swing.JTextField NombreFicheroEscribir;
    private javax.swing.JTextField NombreFicheroLeer;
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel TextoEscribir;
    private javax.swing.JLabel TextoLeer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField panelArchivoLeer;
    // End of variables declaration//GEN-END:variables
}
