/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fichero_secuencial;

import static fichero_secuencial.Fichero_secuencial1.grabarDatos;
import java.awt.Dimension;
import java.io.*;
import javax.swing.JFrame;


/**
 *
 * @author Sergio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocation(300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeerEscribir = new javax.swing.JDialog();
        ArchivoSecuencial1 = new javax.swing.JPanel();
        LeerFichero = new javax.swing.JButton();
        EscribirFichero = new javax.swing.JButton();
        BuscarTexto = new javax.swing.JButton();
        ArchivoLeer = new javax.swing.JPanel();
        AceptarLeer = new javax.swing.JButton();
        NombreFicheroLeer = new javax.swing.JTextField();
        TextoLeer = new javax.swing.JLabel();
        AreaLeer = new javax.swing.JScrollPane();
        AreaLeer1 = new javax.swing.JTextArea();
        ArchivoEscribir = new javax.swing.JPanel();
        AceptarEscribir = new javax.swing.JButton();
        NombreFicheroEscribir = new javax.swing.JTextField();
        TextoEscribir = new javax.swing.JLabel();
        ArchivoEscribir1 = new javax.swing.JPanel();
        EscribirFinal = new javax.swing.JButton();
        Sobreescribir = new javax.swing.JButton();
        ArchivoEscribir2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoEscribir1 = new javax.swing.JTextArea();
        EscribirFinal1 = new javax.swing.JButton();
        ArchivoSobreescribir = new javax.swing.JPanel();
        SobreEscribir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextoSobreescribir = new javax.swing.JTextArea();
        BuscarTexto1 = new javax.swing.JDialog();
        RutaArchivo = new javax.swing.JPanel();
        NombreFichero = new javax.swing.JLabel();
        rutaFichero = new javax.swing.JTextField();
        AceptarFichero = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        CopiarFichero = new javax.swing.JButton();
        CrearFichero = new javax.swing.JButton();
        ArchivoAleatorio = new javax.swing.JButton();
        ArchivoSecuencial = new javax.swing.JButton();

        LeerFichero.setText("Leer Fichero");
        LeerFichero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LeerFicheroMousePressed(evt);
            }
        });
        LeerFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        EscribirFichero.setText("Escribir Fichero");
        EscribirFichero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscribirFicheroMousePressed(evt);
            }
        });

        BuscarTexto.setText("Buscar Texto");
        BuscarTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarTextoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ArchivoSecuencial1Layout = new javax.swing.GroupLayout(ArchivoSecuencial1);
        ArchivoSecuencial1.setLayout(ArchivoSecuencial1Layout);
        ArchivoSecuencial1Layout.setHorizontalGroup(
            ArchivoSecuencial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArchivoSecuencial1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LeerFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(EscribirFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(ArchivoSecuencial1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(BuscarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ArchivoSecuencial1Layout.setVerticalGroup(
            ArchivoSecuencial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoSecuencial1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoSecuencial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscribirFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeerFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BuscarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        AceptarLeer.setText("Aceptar");
        AceptarLeer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AceptarLeerMousePressed(evt);
            }
        });

        NombreFicheroLeer.setText("fichero.txt");

        TextoLeer.setText("Nombre fichero:");

        AreaLeer1.setColumns(20);
        AreaLeer1.setRows(5);
        AreaLeer.setViewportView(AreaLeer1);

        javax.swing.GroupLayout ArchivoLeerLayout = new javax.swing.GroupLayout(ArchivoLeer);
        ArchivoLeer.setLayout(ArchivoLeerLayout);
        ArchivoLeerLayout.setHorizontalGroup(
            ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoLeerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AreaLeer)
                    .addGroup(ArchivoLeerLayout.createSequentialGroup()
                        .addComponent(TextoLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(NombreFicheroLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AceptarLeer)))
                .addContainerGap())
        );
        ArchivoLeerLayout.setVerticalGroup(
            ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoLeerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ArchivoLeerLayout.createSequentialGroup()
                        .addComponent(TextoLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ArchivoLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AceptarLeer)
                        .addComponent(NombreFicheroLeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AreaLeer, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        AceptarEscribir.setText("Aceptar");
        AceptarEscribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AceptarEscribirMousePressed(evt);
            }
        });

        NombreFicheroEscribir.setText("fichero.txt");

        TextoEscribir.setText("Nombre fichero:");

        javax.swing.GroupLayout ArchivoEscribirLayout = new javax.swing.GroupLayout(ArchivoEscribir);
        ArchivoEscribir.setLayout(ArchivoEscribirLayout);
        ArchivoEscribirLayout.setHorizontalGroup(
            ArchivoEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoEscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(NombreFicheroEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AceptarEscribir)
                .addContainerGap())
        );
        ArchivoEscribirLayout.setVerticalGroup(
            ArchivoEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ArchivoEscribirLayout.createSequentialGroup()
                        .addComponent(TextoEscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ArchivoEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AceptarEscribir)
                        .addComponent(NombreFicheroEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        EscribirFinal.setText(" Escribir al final del fichero");
        EscribirFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscribirFinalMousePressed(evt);
            }
        });

        Sobreescribir.setText("Sobreescribir fichero");
        Sobreescribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SobreescribirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ArchivoEscribir1Layout = new javax.swing.GroupLayout(ArchivoEscribir1);
        ArchivoEscribir1.setLayout(ArchivoEscribir1Layout);
        ArchivoEscribir1Layout.setHorizontalGroup(
            ArchivoEscribir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribir1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EscribirFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(Sobreescribir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        ArchivoEscribir1Layout.setVerticalGroup(
            ArchivoEscribir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribir1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(ArchivoEscribir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscribirFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sobreescribir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        TextoEscribir1.setColumns(20);
        TextoEscribir1.setRows(5);
        jScrollPane1.setViewportView(TextoEscribir1);

        EscribirFinal1.setText("EscribirFinal");
        EscribirFinal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscribirFinal1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout ArchivoEscribir2Layout = new javax.swing.GroupLayout(ArchivoEscribir2);
        ArchivoEscribir2.setLayout(ArchivoEscribir2Layout);
        ArchivoEscribir2Layout.setHorizontalGroup(
            ArchivoEscribir2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribir2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoEscribir2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addGroup(ArchivoEscribir2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EscribirFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ArchivoEscribir2Layout.setVerticalGroup(
            ArchivoEscribir2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoEscribir2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EscribirFinal1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        SobreEscribir.setText("SobreEscribir");
        SobreEscribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SobreEscribirMousePressed(evt);
            }
        });

        TextoSobreescribir.setColumns(20);
        TextoSobreescribir.setRows(5);
        jScrollPane2.setViewportView(TextoSobreescribir);

        javax.swing.GroupLayout ArchivoSobreescribirLayout = new javax.swing.GroupLayout(ArchivoSobreescribir);
        ArchivoSobreescribir.setLayout(ArchivoSobreescribirLayout);
        ArchivoSobreescribirLayout.setHorizontalGroup(
            ArchivoSobreescribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoSobreescribirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArchivoSobreescribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(ArchivoSobreescribirLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SobreEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ArchivoSobreescribirLayout.setVerticalGroup(
            ArchivoSobreescribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArchivoSobreescribirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SobreEscribir)
                .addContainerGap())
        );

        javax.swing.GroupLayout LeerEscribirLayout = new javax.swing.GroupLayout(LeerEscribir.getContentPane());
        LeerEscribir.getContentPane().setLayout(LeerEscribirLayout);
        LeerEscribirLayout.setHorizontalGroup(
            LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoLeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoSecuencial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ArchivoEscribir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoEscribir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoSobreescribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        LeerEscribirLayout.setVerticalGroup(
            LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoLeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoSecuencial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ArchivoEscribir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoEscribir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(LeerEscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeerEscribirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArchivoSobreescribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        NombreFichero.setText("Nombre fichero:");

        rutaFichero.setText("fichero.txt");

        AceptarFichero.setText("Aceptar");

        javax.swing.GroupLayout RutaArchivoLayout = new javax.swing.GroupLayout(RutaArchivo);
        RutaArchivo.setLayout(RutaArchivoLayout);
        RutaArchivoLayout.setHorizontalGroup(
            RutaArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RutaArchivoLayout.createSequentialGroup()
                .addComponent(NombreFichero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rutaFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AceptarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        RutaArchivoLayout.setVerticalGroup(
            RutaArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RutaArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RutaArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rutaFichero)
                    .addComponent(NombreFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AceptarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BuscarTexto1Layout = new javax.swing.GroupLayout(BuscarTexto1.getContentPane());
        BuscarTexto1.getContentPane().setLayout(BuscarTexto1Layout);
        BuscarTexto1Layout.setHorizontalGroup(
            BuscarTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarTexto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RutaArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BuscarTexto1Layout.setVerticalGroup(
            BuscarTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarTexto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RutaArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CopiarFichero.setText("Copiar fichero");

        CrearFichero.setText("Crear fichero o carpeta");

        ArchivoAleatorio.setText("Archivo aleatorio");

        ArchivoSecuencial.setText("Archivo secuencial");
        ArchivoSecuencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ArchivoSecuencialMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArchivoSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ArchivoAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(CopiarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArchivoSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(ArchivoAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CrearFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(CopiarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        
    private void ArchivoSecuencialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivoSecuencialMousePressed
        ArchivoLeer.setVisible(false);
        ArchivoEscribir.setVisible(false);
        ArchivoEscribir1.setVisible(false);
        ArchivoEscribir2.setVisible(false);
        ArchivoSobreescribir.setVisible(false);
        
        LeerEscribir.setVisible(true);
        LeerEscribir.setLocation(300, 300);
        LeerEscribir.setSize(400, 300);
        ArchivoSecuencial1.setVisible(true);

    }//GEN-LAST:event_ArchivoSecuencialMousePressed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void LeerFicheroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeerFicheroMousePressed
        ArchivoSecuencial1.setVisible(false);
        ArchivoLeer.setVisible(true);
        LeerEscribir.setSize(488, 310);
        
    }//GEN-LAST:event_LeerFicheroMousePressed

    private void AceptarLeerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarLeerMousePressed
        leerDatos(NombreFicheroLeer.getText());
        
    }//GEN-LAST:event_AceptarLeerMousePressed

    private void EscribirFicheroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscribirFicheroMousePressed
        ArchivoSecuencial1.setVisible(false);
        ArchivoEscribir.setVisible(true);
        ArchivoEscribir.setLocation(300, 300);
        LeerEscribir.setSize(488, 91);
    }//GEN-LAST:event_EscribirFicheroMousePressed

    private void AceptarEscribirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarEscribirMousePressed
        rutaFichero(NombreFicheroEscribir.getText());
    }//GEN-LAST:event_AceptarEscribirMousePressed

    private void EscribirFinalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscribirFinalMousePressed
        ArchivoEscribir1.setVisible(false);
        ArchivoEscribir2.setVisible(true);
        
    }//GEN-LAST:event_EscribirFinalMousePressed

    private void SobreescribirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SobreescribirMousePressed
        ArchivoEscribir1.setVisible(false);
        ArchivoSobreescribir.setVisible(true);

    }//GEN-LAST:event_SobreescribirMousePressed

    private void EscribirFinal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscribirFinal1MousePressed
        grabarDatos(NombreFicheroEscribir.getText(), TextoEscribir1.getText());
    }//GEN-LAST:event_EscribirFinal1MousePressed

    private void SobreEscribirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SobreEscribirMousePressed
        grabarDatos1(NombreFicheroEscribir.getText(), TextoSobreescribir.getText());
    }//GEN-LAST:event_SobreEscribirMousePressed

    private void BuscarTextoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarTextoMousePressed
        ArchivoSecuencial1.setVisible(false);
        LeerEscribir.setVisible(false);
        BuscarTexto1.setVisible(true);
        BuscarTexto1.setSize(488, 93);
        BuscarTexto1.setLocation(300, 300);
    }//GEN-LAST:event_BuscarTextoMousePressed
    
    
    public void grabarDatos1(String archivo, String datos){
        try{

            FileWriter fw = new FileWriter(archivo,false);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(datos + "\n");
             bw.close();
             }
        catch(java.io.IOException ioex){}
    } 
    
    public void grabarDatos(String archivo, String datos){
        try{

            FileWriter fw = new FileWriter(archivo,true);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(datos + "\n");
             bw.close();
             }
        catch(java.io.IOException ioex){}
    } 
    
    
    public void rutaFichero(String archivo){
        try{
            FileReader fr = new FileReader(archivo);
            BufferedReader entrada = new BufferedReader(fr);
            ArchivoEscribir.setVisible(false);
            ArchivoEscribir1.setVisible(true);
            ArchivoEscribir1.setLocation(300, 300);
            LeerEscribir.setSize(400, 300);
        }
        
        catch(java.io.FileNotFoundException fnfex){
        System.out.println("Archivo no encontrado!!!"); 
        }
        catch(java.io.IOException ioex){}
    }

    public void leerDatos(String archivo){
        
        
        try{
            String texto= new String();
            FileReader fr = new FileReader(archivo);
            BufferedReader entrada = new BufferedReader(fr);
            String s;
            
            
            while((s = entrada.readLine() )!=null)
                texto += s ;
            
            AreaLeer1.setText("Datos leidos del archivo:"
                     + "\n" + texto + "\n" + "tamaño del fichero: \n"+texto.length());
          
            System.out.print((char) entrada.read());
            entrada.close();
            
        }
        
        catch(java.io.FileNotFoundException fnfex){   
        System.out.println("Archivo no encontrado!!!"); 
        }
        catch(java.io.IOException ioex){} 
        }
    
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarEscribir;
    private javax.swing.JButton AceptarFichero;
    private javax.swing.JButton AceptarLeer;
    private javax.swing.JButton ArchivoAleatorio;
    private javax.swing.JPanel ArchivoEscribir;
    private javax.swing.JPanel ArchivoEscribir1;
    private javax.swing.JPanel ArchivoEscribir2;
    private javax.swing.JPanel ArchivoLeer;
    private javax.swing.JButton ArchivoSecuencial;
    private javax.swing.JPanel ArchivoSecuencial1;
    private javax.swing.JPanel ArchivoSobreescribir;
    private javax.swing.JScrollPane AreaLeer;
    private javax.swing.JTextArea AreaLeer1;
    private javax.swing.JButton BuscarTexto;
    private javax.swing.JDialog BuscarTexto1;
    private javax.swing.JButton CopiarFichero;
    private javax.swing.JButton CrearFichero;
    private javax.swing.JButton EscribirFichero;
    private javax.swing.JButton EscribirFinal;
    private javax.swing.JButton EscribirFinal1;
    private javax.swing.JDialog LeerEscribir;
    private javax.swing.JButton LeerFichero;
    private javax.swing.JLabel NombreFichero;
    private javax.swing.JTextField NombreFicheroEscribir;
    private javax.swing.JTextField NombreFicheroLeer;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel RutaArchivo;
    private javax.swing.JButton SobreEscribir;
    private javax.swing.JButton Sobreescribir;
    private javax.swing.JLabel TextoEscribir;
    private javax.swing.JTextArea TextoEscribir1;
    private javax.swing.JLabel TextoLeer;
    private javax.swing.JTextArea TextoSobreescribir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField rutaFichero;
    // End of variables declaration//GEN-END:variables
}
