/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fichero_secuencial;

import static fichero_secuencial.Fichero_secuencial1.grabarDatos;
import java.io.*;
import javax.swing.JFrame;


/**
 *
 * @author Sergio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoLeido = new javax.swing.JDialog();
        Escribir = new javax.swing.JButton();
        Leer = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        CopiarFichero = new javax.swing.JButton();
        CrearFichero = new javax.swing.JButton();
        ArchivoAleatorio = new javax.swing.JButton();
        ArchivoSecuencial = new javax.swing.JButton();

        Escribir.setText("Escribir");
        Escribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscribirMousePressed(evt);
            }
        });
        Escribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirActionPerformed(evt);
            }
        });

        Leer.setText("Leer");
        Leer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LeerMousePressed(evt);
            }
        });
        Leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        javax.swing.GroupLayout TextoLeidoLayout = new javax.swing.GroupLayout(TextoLeido.getContentPane());
        TextoLeido.getContentPane().setLayout(TextoLeidoLayout);
        TextoLeidoLayout.setHorizontalGroup(
            TextoLeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(TextoLeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TextoLeidoLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Leer, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                    .addComponent(Escribir, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        TextoLeidoLayout.setVerticalGroup(
            TextoLeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(TextoLeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TextoLeidoLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addGroup(TextoLeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Leer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Escribir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(97, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CopiarFichero.setText("Copiar fichero");

        CrearFichero.setText("Crear fichero o carpeta");

        ArchivoAleatorio.setText("Archivo aleatorio");

        ArchivoSecuencial.setText("Archivo secuencial");
        ArchivoSecuencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ArchivoSecuencialMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArchivoSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ArchivoAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(CopiarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArchivoSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(ArchivoAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CrearFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(CopiarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void EscribirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscribirMousePressed
        grabarDatos("C:\\Users\\Sergio\\Desktop\\UFV\\Acceso a Datos\\fichero1.txt","asdfadsfvsdcasd,asdofijasdof");
    }//GEN-LAST:event_EscribirMousePressed
    
    private void LeerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeerMousePressed
        leerDatos("C:\\Users\\Sergio\\Desktop\\UFV\\Acceso a Datos\\fichero1.txt");
    }//GEN-LAST:event_LeerMousePressed

    private void EscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirActionPerformed

    private void ArchivoSecuencialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivoSecuencialMousePressed
        TextoLeido.setVisible(true);
        
        TextoLeido.setSize(400, 300);
    }//GEN-LAST:event_ArchivoSecuencialMousePressed
    
    
    
    public static void grabarDatos(String archivo, String datos){
        try{

            FileWriter fw = new FileWriter(archivo,false);

            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(datos + "\n");
             bw.close();
             }
        catch(java.io.IOException ioex){}
    } 
    
    public static void leerDatos(String archivo){
        try{
            String texto= new String();
            FileReader fr = new FileReader(archivo);
            BufferedReader entrada = new BufferedReader(fr);
            String s;
            
            
            while((s = entrada.readLine() )!=null)
                texto += s + "\n";
            System.out.println("\nDatos leidos del archivo con READLINE:"
                     + " \n" + texto + "tamaño del fichero: \n"+texto.length());
          
            System.out.print((char) entrada.read());
            entrada.close();
        
        }
        
        catch(java.io.FileNotFoundException fnfex){   
        System.out.println("Archivo no encontrado!!!"); 
        }
        catch(java.io.IOException ioex){} 
        }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArchivoAleatorio;
    private javax.swing.JButton ArchivoSecuencial;
    private javax.swing.JButton CopiarFichero;
    private javax.swing.JButton CrearFichero;
    private javax.swing.JButton Escribir;
    private javax.swing.JButton Leer;
    private javax.swing.JPanel Panel1;
    private javax.swing.JDialog TextoLeido;
    // End of variables declaration//GEN-END:variables
}
